name = "MyJuliaRegistry"
uuid = "2590fab8-ff9e-4ab0-a483-288e40ae7ee3"
repo = "git@github.com:sojoasd/My-Julia.git"

[packages]
52655ab5-b29d-45fc-a133-0c293715c2a1 = { name = "FindRoot", path = "F/FindRoot" }
