name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the package'
        required: true
        default: 'MyPackage'
      package_version:
        description: 'The version of the package'
        required: true
        default: '0.1.0'

jobs:
  pkg-test:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: ${{ github.event.inputs.package_name }}
      PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Julia 1.10
        uses: julia-actions/setup-julia@v2
        with:
          version: 1.10
      - name: Run test script
        run: |
          echo "Running tests for $PACKAGE_NAME version $PACKAGE_VERSION"
          echo "julia --project testPkg.jl $PACKAGE_NAME"

  pkg-registry:
    needs: pkg-test
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: ${{ github.event.inputs.package_name }}
      PACKAGE_VERSION: ${{ github.event.inputs.package_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo "Registering $PACKAGE_NAME version $PACKAGE_VERSION"
