name: CI

on:
  # 符合 /^release\/.*$/ 模式的 tag
  push:
    tags:
      - 'release/**'  

jobs:
  pkg-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Build triggered by release tag!"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
